name: freezed_bloc_error_reproduction
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.0
  lints: ^2.0.0
  test: ^1.21.0
